### ISSUE TITLE
有个文不对题的bug

### ISSUE THREAD

**Issue by fcjz** [HCWiki/HCWiki.github.io#1]
兄弟，你那个标题为“不要买付费识别码的五个理由”的tiddler正文第一段话写的是“让我告诉你，不要购买付费识别码的十个理由“。

到底是5个理由还是10个理由？

你正文几段的理由一共是5个，我怀疑你写错了。

聊天室我懒得去，估计以后也不会去了……可能还是会去一下的？关键是很累，那里没啥正经聊天的，不是抗战就是挂机。

有事联系我邮箱：imagine-cyf@yandex.com，我肯定会看见，肯定会回。

对于8、9日发生的事情，我问过很多人，除了鱼和小张告诉我一个大概之外，pig和阿哲他们的态度是”你没必要知道那么多“，我越发觉得聊天室无趣了，对于这里从古至今所发生的所有事情，我始终持中立吃瓜态度。

**Comment by xjzh123** [comment]
已修复
